default_environment: default
environments:
    default:
        connections:
            motherduck:
                - name: "motherduck-default"
                  token: ${MOTHERDUCK_TOKEN}
                  database: "epa-air-quality"
